name: i18n

on:
  push:
    branches:
      - main
    paths:
      - locales/en.json
      - i18n.yml

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  i18n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: theJian/deepseek-translator@v1
        with:
          deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}
      - uses: peter-evans/create-pull-request@v7
